[package]
name = "from-num"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0.10"
seq-macro = "0.3.5"
proc-macro2 = "1.0.68"
syn = "2.0.38"
quote = "1.0.33"

[lib]
proc-macro = true