[package]
name = "from-num"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "*"
seq-macro = "*"
proc-macro2 = "*"
syn = "*"
quote = "*"

[lib]
proc-macro = true